
# Task Analysis {.appendix}

## Prerequisites

The most basic prerequisite for this user guide is having R and RStudio installed on a computer. The user will also need a properly formatted csv file stored in a folder. Other useful knowledge includes:

- very very basic R (how to create a new file, run commands, etc.)
- an understanding of the structure of dataframes
- an understanding of basic data types (string, integer, float) and numerical vs categorical variables

## Data Requirements

There are no basic data requirements beyond being stored in csv format. The point of this user guide is to clean up messy data.

## Basic Components of the Task 

1. **Import data into RStudio**
  a. Change the working directory to the folder that stores the data 
  b. Use read.csv to store data in a variable
  c. Take a peek at the first few rows of the df to make sure it worked
  
2. **Remove duplicates**
  a. Locate the duplicate rows
  b. Drop the duplicate rows
  
3. **Change columns to the correct data type**
  a. Identify the data types of each column
  b. Decide which column types need to be changed (categorical vs numerical)
  c. Change the identified columns to the correct data type
  
4. **Identify and correct missing values**
  a. Locate the columns containing missing values
  b. **(Option 1) Imputing Missing Values:**
    (1) Calculate the mean/mode for each column that has missing values.
    (2) Change the missing values in each column to its respective mean/mode.
  c. **(Option 2) Dropping Missing Values:**
    (1) Drop the rows that have missing values in the identified columns.

## User Decisions

There are two decisions that the user will have to make for themselves. First, they need to decide which columns are of the wrong data type and what they should be changed to. Second, they will have to decide whether rows with missing values can be dropped or if they should be kept, imputing the missing values.

## Quality Checks After Task is Completed

- **Check that the shape of the dataframe is roughly the same**. Or if many rows were dropped, make sure that the new shape is reasonable. If there are too few rows, go back and impute the missing values instead.
- **Do the imputed values look correct?** Are the means/modes reasonable in the context of the data?
- **Confirm that the data types of each column are correct.**
- **Confirm that there are no duplicate rows anymore.**
